version: "3.7"

secrets:
  db_replica_password:
    external: true

networks:
  default:

volumes:
  app_data:
  db_data:

services:
  app:
    image: mattermost/mattermost-prod-app:5.23.1
    volumes:
      - app_data:/mattermost
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3203:8000"
    environment:
      - edition=team
      - DB_HOST=db
      - DB_PORT_NUMBER=5432
      - MM_DBNAME=mattermost
      - MM_USERNAME=mmuser
      - MM_PASSWORD=123456
      - MM_PLUGINSETTINGS_ENABLEUPLOADS=true
    deploy:
      placement:
        constraints:
          - node.labels.type == primary
  db:
    image: pg94master
    volumes:
      - db_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=mattermost
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=123456
      - PG_REP_USER=replication
      - PG_REP_PASSWORD_FILE=/run/secrets/db_replica_password
      - HBA_ADDRESS=10.0.0.0/8
    ports:
      - "5432:5432"
    secrets:
      - db_replica_password
    deploy:
      placement:
        constraints:
          - node.labels.type == primary
  db_slave:
    image: mesoform/pg94slave:version-1.0.1
    environment:
      - POSTGRES_DB=mattermost
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=123456
      - PG_REP_USER=replication
      - PG_REP_PASSWORD_FILE=/run/secrets/db_replica_password
      - PG_MASTER_HOST=db  # This needs to be the swarm node private IP instead of the service name (pg_master) which resolves to the service IP
      - HBA_ADDRESS=10.0.0.0/8
    secrets:
      - db_replica_password
    networks:
      default:
    deploy:
      placement:
        constraints:
        - node.labels.type != primary
