version: "3.7"

networks:
  default:

volumes:
  app_data:
  db_data:

services:
  app:
    image: mattermost/mattermost-prod-app:5.23.1
    volumes:
      - app_data:/mattermost
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3203:8000"
    environment:
      - edition=team
      - DB_HOST=db
      - DB_PORT_NUMBER=5432
      - MM_DBNAME=mattermost
      - MM_USERNAME=mmuser
      - MM_PASSWORD=123456
      - MM_PLUGINSETTINGS_ENABLEUPLOADS=true
    deploy:
      placement:
        constraints:
          - node.labels.type == primary
  db:
    image: mattermost/mattermost-prod-db
    volumes:
      - db_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=mattermost
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints:
          - node.labels.type == primary
